/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Erlinda
 */
public class ResultadosContenidoPanel extends javax.swing.JPanel {

    /**
     * Creates new form ResultadosContenidoPanel
     */
    public ResultadosContenidoPanel() {
        initComponents();
    }

    public void paint(Graphics g) {
        Image imagen = new ImageIcon(getClass().getResource("/img/fondo2.jpg")).getImage();
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        setOpaque(false);
        super.paint(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAbrirPdf = new javax.swing.JButton();
        buttonImprimir = new javax.swing.JButton();
        jPanelExplicacionRecomFertilizacion = new javax.swing.JPanel();
        jLabelExplicacionFertiTextura = new javax.swing.JLabel();
        jLabelExplicacionFertiNitrogeno = new javax.swing.JLabel();
        jLabelExplicacionFertiFosforo = new javax.swing.JLabel();
        jLabelExplicacionFertiPotasio = new javax.swing.JLabel();
        resultadosRecFertilizacionPanel1 = new view.ResultadosRecFertilizacionPanel();

        buttonAbrirPdf.setText("Abrir PDF");

        buttonImprimir.setText("Imprimir");

        jPanelExplicacionRecomFertilizacion.setBackground(new java.awt.Color(255, 255, 255));
        jPanelExplicacionRecomFertilizacion.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelExplicacionFertiTextura.setText("jLabel1");

        jLabelExplicacionFertiNitrogeno.setText("jLabel1");

        jLabelExplicacionFertiFosforo.setText("jLabel2");

        jLabelExplicacionFertiPotasio.setText("jLabel3");

        javax.swing.GroupLayout jPanelExplicacionRecomFertilizacionLayout = new javax.swing.GroupLayout(jPanelExplicacionRecomFertilizacion);
        jPanelExplicacionRecomFertilizacion.setLayout(jPanelExplicacionRecomFertilizacionLayout);
        jPanelExplicacionRecomFertilizacionLayout.setHorizontalGroup(
            jPanelExplicacionRecomFertilizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExplicacionRecomFertilizacionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelExplicacionRecomFertilizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelExplicacionFertiPotasio, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelExplicacionFertiFosforo, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelExplicacionFertiNitrogeno, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelExplicacionFertiTextura, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanelExplicacionRecomFertilizacionLayout.setVerticalGroup(
            jPanelExplicacionRecomFertilizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExplicacionRecomFertilizacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelExplicacionFertiTextura, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabelExplicacionFertiNitrogeno, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabelExplicacionFertiFosforo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabelExplicacionFertiPotasio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelExplicacionRecomFertilizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(buttonAbrirPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(buttonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultadosRecFertilizacionPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resultadosRecFertilizacionPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelExplicacionRecomFertilizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAbrirPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buttonAbrirPdf;
    public javax.swing.JButton buttonImprimir;
    public javax.swing.JLabel jLabelExplicacionFertiFosforo;
    public javax.swing.JLabel jLabelExplicacionFertiNitrogeno;
    public javax.swing.JLabel jLabelExplicacionFertiPotasio;
    public javax.swing.JLabel jLabelExplicacionFertiTextura;
    public javax.swing.JPanel jPanelExplicacionRecomFertilizacion;
    public view.ResultadosRecFertilizacionPanel resultadosRecFertilizacionPanel1;
    // End of variables declaration//GEN-END:variables
}
