/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sinLabView;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;

/**
 *
 * @author Erlinda
 */
public class FosforoPanel extends javax.swing.JPanel {

    /**
     * Creates new form JPPreguntaFosforoNA
     */
    public FosforoPanel() {
        initComponents();
    }

    public void paint(Graphics g) {
        Image imagen = new ImageIcon(getClass().getResource("/img/fondo1.jpg")).getImage();
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        setOpaque(false);
        super.paint(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupFosforo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonFosfoHigh = new javax.swing.JRadioButton();
        jRadioButtonFosfoMedium = new javax.swing.JRadioButton();
        jRadioButtonFosfoLow = new javax.swing.JRadioButton();
        jRadioButtonFosfoTrace = new javax.swing.JRadioButton();
        jRadioButtonFosfoTraceLow = new javax.swing.JRadioButton();
        jRadioButtonFosfoLowMedium = new javax.swing.JRadioButton();
        jRadioButtonFosfoMediumHigh = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fosforoInformacionPanel1 = new view.sinLabView.FosforoInformacionPanel();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Elija el color de fosforo encontrado en el Suelo");

        buttonGroupFosforo.add(jRadioButtonFosfoHigh);
        jRadioButtonFosfoHigh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButtonFosfoHigh.setText("High");
        jRadioButtonFosfoHigh.setOpaque(false);
        jRadioButtonFosfoHigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFosfoHighActionPerformed(evt);
            }
        });

        buttonGroupFosforo.add(jRadioButtonFosfoMedium);
        jRadioButtonFosfoMedium.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButtonFosfoMedium.setText("Medium");
        jRadioButtonFosfoMedium.setOpaque(false);

        buttonGroupFosforo.add(jRadioButtonFosfoLow);
        jRadioButtonFosfoLow.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButtonFosfoLow.setText("Low");
        jRadioButtonFosfoLow.setOpaque(false);

        buttonGroupFosforo.add(jRadioButtonFosfoTrace);
        jRadioButtonFosfoTrace.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButtonFosfoTrace.setText("Trace");
        jRadioButtonFosfoTrace.setOpaque(false);
        jRadioButtonFosfoTrace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFosfoTraceActionPerformed(evt);
            }
        });

        buttonGroupFosforo.add(jRadioButtonFosfoTraceLow);
        jRadioButtonFosfoTraceLow.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButtonFosfoTraceLow.setText("Entre Low - Trace");
        jRadioButtonFosfoTraceLow.setOpaque(false);

        buttonGroupFosforo.add(jRadioButtonFosfoLowMedium);
        jRadioButtonFosfoLowMedium.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButtonFosfoLowMedium.setText("Entre Medium - Low");
        jRadioButtonFosfoLowMedium.setOpaque(false);

        buttonGroupFosforo.add(jRadioButtonFosfoMediumHigh);
        jRadioButtonFosfoMediumHigh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButtonFosfoMediumHigh.setText("Entre High - Medium");
        jRadioButtonFosfoMediumHigh.setOpaque(false);

        jLabel2.setBackground(new java.awt.Color(92, 136, 218));
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(220, 240, 240));
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(167, 198, 237));
        jLabel4.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(16, 6, 159));
        jLabel5.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonFosfoTrace)
                                    .addComponent(jRadioButtonFosfoHigh)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButtonFosfoMedium, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jRadioButtonFosfoLow)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jRadioButtonFosfoMediumHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButtonFosfoLowMedium)
                            .addComponent(jRadioButtonFosfoTraceLow))
                        .addGap(66, 66, 66)
                        .addComponent(fosforoInformacionPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(jRadioButtonFosfoTrace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(jRadioButtonFosfoLow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(jRadioButtonFosfoMedium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonFosfoHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jRadioButtonFosfoTraceLow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonFosfoLowMedium)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonFosfoMediumHigh))
                    .addComponent(fosforoInformacionPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonFosfoHighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFosfoHighActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFosfoHighActionPerformed

    private void jRadioButtonFosfoTraceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFosfoTraceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFosfoTraceActionPerformed

    public ButtonGroup getButtonGroupFosforo() {
        return buttonGroupFosforo;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupFosforo;
    private view.sinLabView.FosforoInformacionPanel fosforoInformacionPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JRadioButton jRadioButtonFosfoHigh;
    public javax.swing.JRadioButton jRadioButtonFosfoLow;
    public javax.swing.JRadioButton jRadioButtonFosfoLowMedium;
    public javax.swing.JRadioButton jRadioButtonFosfoMedium;
    public javax.swing.JRadioButton jRadioButtonFosfoMediumHigh;
    public javax.swing.JRadioButton jRadioButtonFosfoTrace;
    public javax.swing.JRadioButton jRadioButtonFosfoTraceLow;
    // End of variables declaration//GEN-END:variables
}
