/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sinLabView;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;

/**
 *
 * @author Erlinda
 */
public class PHPanel extends javax.swing.JPanel {

    /**
     * Creates new form JPPreguntaPH
     */
    public PHPanel() {
        initComponents();
    }

    public void paint(Graphics g) {
        Image imagen = new ImageIcon(getClass().getResource("/img/fondo1.jpg")).getImage();
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        setOpaque(false);
        super.paint(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPh = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonPh4 = new javax.swing.JRadioButton();
        jRadioButtonPh5 = new javax.swing.JRadioButton();
        jRadioButtonPh6 = new javax.swing.JRadioButton();
        jRadioButtonpH9 = new javax.swing.JRadioButton();
        jRadioButtonpH8 = new javax.swing.JRadioButton();
        jRadioButtonPh7 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        phInformacionPanel1 = new view.sinLabView.PhInformacionPanel();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Elija el color de pH encontrado en la prueba");

        buttonGroupPh.add(jRadioButtonPh4);
        jRadioButtonPh4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButtonPh4.setText("  pH 4");
        jRadioButtonPh4.setOpaque(false);

        buttonGroupPh.add(jRadioButtonPh5);
        jRadioButtonPh5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButtonPh5.setText("  pH 5");
        jRadioButtonPh5.setOpaque(false);

        buttonGroupPh.add(jRadioButtonPh6);
        jRadioButtonPh6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButtonPh6.setText("  pH 6");
        jRadioButtonPh6.setOpaque(false);

        buttonGroupPh.add(jRadioButtonpH9);
        jRadioButtonpH9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButtonpH9.setText("  pH 9");
        jRadioButtonpH9.setOpaque(false);
        jRadioButtonpH9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonpH9ActionPerformed(evt);
            }
        });

        buttonGroupPh.add(jRadioButtonpH8);
        jRadioButtonpH8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButtonpH8.setText("  pH 8");
        jRadioButtonpH8.setOpaque(false);

        buttonGroupPh.add(jRadioButtonPh7);
        jRadioButtonPh7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButtonPh7.setText("  pH 7");
        jRadioButtonPh7.setOpaque(false);
        jRadioButtonPh7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPh7ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 0));
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(151, 215, 0));
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(0, 102, 0));
        jLabel4.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(0, 102, 102));
        jLabel5.setOpaque(true);

        jLabel6.setBackground(new java.awt.Color(0, 0, 204));
        jLabel6.setOpaque(true);

        jLabel7.setBackground(new java.awt.Color(0, 0, 102));
        jLabel7.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonPh5)
                    .addComponent(jRadioButtonPh4)
                    .addComponent(jRadioButtonPh6)
                    .addComponent(jRadioButtonPh7)
                    .addComponent(jRadioButtonpH8)
                    .addComponent(jRadioButtonpH9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(phInformacionPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 608, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phInformacionPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(jRadioButtonPh4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(jRadioButtonPh5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(jRadioButtonPh6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonPh7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonpH8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonpH9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonpH9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonpH9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonpH9ActionPerformed

    private void jRadioButtonPh7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPh7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPh7ActionPerformed

    public ButtonGroup getButtonGroupPh() {
        return buttonGroupPh;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupPh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JRadioButton jRadioButtonPh4;
    public javax.swing.JRadioButton jRadioButtonPh5;
    public javax.swing.JRadioButton jRadioButtonPh6;
    public javax.swing.JRadioButton jRadioButtonPh7;
    public javax.swing.JRadioButton jRadioButtonpH8;
    public javax.swing.JRadioButton jRadioButtonpH9;
    private view.sinLabView.PhInformacionPanel phInformacionPanel1;
    // End of variables declaration//GEN-END:variables
}
