/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sinLabView;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Erlinda
 */
public class TexturaPanel extends javax.swing.JPanel {

    /**
     * Creates new form JPPreguntasNA
     */
    public TexturaPanel() {
        initComponents();
    }

    public void paint(Graphics g) {
        Image imagen = new ImageIcon(getClass().getResource("/img/fondo1.jpg")).getImage();
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        setOpaque(false);
        super.paint(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPreguntaTextura = new javax.swing.JLabel();
        jLabelProfundidadArena = new javax.swing.JLabel();
        jLabelProfundidadLimo = new javax.swing.JLabel();
        jLabelProfundidadArcilla = new javax.swing.JLabel();
        jSpinnerArena = new javax.swing.JSpinner();
        jSpinnerLimo = new javax.swing.JSpinner();
        jSpinnerArcilla = new javax.swing.JSpinner();
        jLabelTexturaTotal = new javax.swing.JLabel();
        jSpinnerTexturaTotal = new javax.swing.JSpinner();
        texturaInformacionPanel2 = new view.sinLabView.TexturaInformacionPanel();
        memoriaTrabajosinLABPanel1 = new view.sinLabView.MemoriaTrabajosinLABPanel();

        jLabelPreguntaTextura.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelPreguntaTextura.setText("Ingrese la proporción de arena,Limo y Arcilla determinado:  ");

        jLabelProfundidadArena.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelProfundidadArena.setText("Profundidad Arena :");

        jLabelProfundidadLimo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelProfundidadLimo.setText("Profundidad Limo   :");

        jLabelProfundidadArcilla.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelProfundidadArcilla.setText("Profundidad Arcilla :");

        jSpinnerArcilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSpinnerArcillaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jSpinnerArcillaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinnerArcillaKeyTyped(evt);
            }
        });

        jLabelTexturaTotal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelTexturaTotal.setText("Total Profundidad Textura :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPreguntaTextura)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelProfundidadArena)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerArena, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelProfundidadLimo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerLimo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelProfundidadArcilla)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerArcilla, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(memoriaTrabajosinLABPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTexturaTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerTexturaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(texturaInformacionPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelPreguntaTextura)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelProfundidadArena, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerArena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelProfundidadLimo)
                            .addComponent(jSpinnerLimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelProfundidadArcilla)
                            .addComponent(jSpinnerArcilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTexturaTotal)
                            .addComponent(jSpinnerTexturaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(memoriaTrabajosinLABPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(texturaInformacionPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinnerArcillaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerArcillaKeyPressed
        // TODO add your handling code here:
        System.out.println("precionando una tecla");
    }//GEN-LAST:event_jSpinnerArcillaKeyPressed

    private void jSpinnerArcillaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerArcillaKeyTyped
        // TODO add your handling code here:
        System.out.println("precionando una tecla typed");
    }//GEN-LAST:event_jSpinnerArcillaKeyTyped

    private void jSpinnerArcillaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerArcillaKeyReleased
        // TODO add your handling code here:
        System.out.println("precionando una tecla released");
    }//GEN-LAST:event_jSpinnerArcillaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabelPreguntaTextura;
    public javax.swing.JLabel jLabelProfundidadArcilla;
    public javax.swing.JLabel jLabelProfundidadArena;
    public javax.swing.JLabel jLabelProfundidadLimo;
    public javax.swing.JLabel jLabelTexturaTotal;
    public javax.swing.JSpinner jSpinnerArcilla;
    public javax.swing.JSpinner jSpinnerArena;
    public javax.swing.JSpinner jSpinnerLimo;
    public javax.swing.JSpinner jSpinnerTexturaTotal;
    public view.sinLabView.MemoriaTrabajosinLABPanel memoriaTrabajosinLABPanel1;
    private view.sinLabView.TexturaInformacionPanel texturaInformacionPanel2;
    // End of variables declaration//GEN-END:variables
}
