/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.ConLabView;

import view.sinLabView.MemoriaTrabajosinLABPanel;
import view.sinLabView.MemoriaTrabajosinLABPanelController;

/**
 *
 * @author Erlinda
 */
public class JFramePrueba extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrueba
     */
    public JFramePrueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelExplicacionRecomFertilizacion = new javax.swing.JPanel();
        jLabelExplicacionFertiTextura = new javax.swing.JLabel();
        jLabelExplicacionFertiNitrogeno = new javax.swing.JLabel();
        jLabelExplicacionFertiFosforo = new javax.swing.JLabel();
        jLabelExplicacionFertiPotasio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelExplicacionRecomFertilizacion.setBackground(new java.awt.Color(255, 255, 255));
        jPanelExplicacionRecomFertilizacion.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelExplicacionFertiTextura.setText("jLabel1");

        jLabelExplicacionFertiNitrogeno.setText("jLabel1");

        jLabelExplicacionFertiFosforo.setText("jLabel2");

        jLabelExplicacionFertiPotasio.setText("jLabel3");

        javax.swing.GroupLayout jPanelExplicacionRecomFertilizacionLayout = new javax.swing.GroupLayout(jPanelExplicacionRecomFertilizacion);
        jPanelExplicacionRecomFertilizacion.setLayout(jPanelExplicacionRecomFertilizacionLayout);
        jPanelExplicacionRecomFertilizacionLayout.setHorizontalGroup(
            jPanelExplicacionRecomFertilizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExplicacionRecomFertilizacionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelExplicacionRecomFertilizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelExplicacionFertiPotasio, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelExplicacionFertiFosforo, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelExplicacionFertiNitrogeno, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelExplicacionFertiTextura, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanelExplicacionRecomFertilizacionLayout.setVerticalGroup(
            jPanelExplicacionRecomFertilizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExplicacionRecomFertilizacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelExplicacionFertiTextura, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelExplicacionFertiNitrogeno, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabelExplicacionFertiFosforo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelExplicacionFertiPotasio, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelExplicacionRecomFertilizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(107, 107, 107)
                    .addComponent(jPanelExplicacionRecomFertilizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(107, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JFramePrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JFramePrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JFramePrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JFramePrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                JFramePrueba jFramePrueba= new JFramePrueba();
//                jFramePrueba.setVisible(true);
//                MemoriaTrabajosinLABPanel memoriaTrabajoPanel=jFramePrueba.memoriaTrabajosinLABPanel1;
//                MemoriaTrabajosinLABPanelController memoriaTrabajoPanelController= new MemoriaTrabajosinLABPanelController(memoriaTrabajoPanel);
//               
//                
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabelExplicacionFertiFosforo;
    public javax.swing.JLabel jLabelExplicacionFertiNitrogeno;
    public javax.swing.JLabel jLabelExplicacionFertiPotasio;
    public javax.swing.JLabel jLabelExplicacionFertiTextura;
    public javax.swing.JPanel jPanelExplicacionRecomFertilizacion;
    // End of variables declaration//GEN-END:variables
}
