package rules 
import model.Cultivo;
rule "Nivel de MO Muy Alto"
    when
        $c : Cultivo( nivelMO >= 120 && <=110 )
    then
        $c.setRangoNivelMO("Muy Alto");
end

rule "Nivel de MO Super bajo"
    when
        $c : Cultivo( nivelMO >= 10 && <=0 )
    then
        $c.setRangoNivelMO("Super Bajo");
end

rule "Nivel de MO Regular"
    when
        $c : Cultivo( nivelMO >= 50 && <=30 )
    then
        $c.setRangoNivelMO("Regular");
end

