package rules 
import model.Cultivo;
rule "Nivel de Fosforo Muy Alto"
    when
        $c : Cultivo( nivelFosforo >= 110 && <=120 )
    then
        $c.setRangoNivelFosforo("Muy Alto");
end

rule "Nivel de Fosforo Super bajo"
    when
        $c : Cultivo( nivelFosforo >= 0 && <=10 )
    then
        $c.setRangoNivelFosforo("Super Bajo");
end

rule "Nivel de Fosforo Regular"
    when
        $c : Cultivo( nivelFosforo >= 30 && <=50 )
    then
        $c.setRangoNivelFosforo("Regular");
end

rule "ddddddddddddddd"
    when
        $c : Cultivo( nivelFosforo >= 23 && <=43 )
    then
        $c.setRangoNivelFosforo("ddddddddddddddddddddaaa");
end

