package rules 
import model.Cultivo;
rule "Nivel de Potasio Muy Alto"
    when
        $c : Cultivo( nivelPotasio >= 120 && <=110 )
    then
        $c.setRangoNivelPotasio("Muy Alto");
end

rule "Nivel de potasio Super bajo"
    when
        $c : Cultivo( nivelPotasio >= 10 && <=0 )
    then
        $c.setRangoNivelPotasio("Super Bajo");
end

rule "Nivel de potasio Regular"
    when
        $c : Cultivo( nivelPotasio >= 50 && <=30 )
    then
        $c.setRangoNivelPotasio("Regular");
end

