package rules 
import model.Cultivo;
rule "Nivel de ph Muy Alto"
    when
        $c : Cultivo( nivelpH >= 110 && <=120 )
    then
        $c.setTipoSuelo("Muy Alto");
end

rule "Nivel de ph Super bajo"
    when
        $c : Cultivo( nivelpH >= 0 && <=10 )
    then
        $c.setTipoSuelo("Super Bajo");
end

rule "Nivel de ph Regular"
    when
        $c : Cultivo( nivelpH >= 30 && <=50 )
    then
        $c.setTipoSuelo("Regular");
end

rule "sssssssssssssssssssss"
    when
        $c : Cultivo( nivelpH >= 12 && <=34 )
    then
        $c.setTipoSuelo("fdhreytr");
end

