/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.OtrasRecomendaciones;

import javax.swing.JFrame;

/**
 *
 * @author Erlinda
 */
public class NewJFramePruebaRecomendaciones extends javax.swing.JFrame {

    /**
     * Creates new form NewJFramePruebaRecomendaciones
     */
    public NewJFramePruebaRecomendaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        otrasRecomendacionesPanel1 = new view.OtrasRecomendaciones.OtrasRecomendacionesPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(otrasRecomendacionesPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(otrasRecomendacionesPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        NewJFramePruebaRecomendaciones newJFramePruebaRecomendaciones = new NewJFramePruebaRecomendaciones();
        newJFramePruebaRecomendaciones.setVisible(true);

        MateriaOrganicaRecomendacionPanel materiaOrganicaRecPanel = newJFramePruebaRecomendaciones.otrasRecomendacionesPanel1.materiaOrganicaRecPanel1;
        MateriaOrganicaRecomendacionPanelController materiaOrganicaRecPanelController = new MateriaOrganicaRecomendacionPanelController(materiaOrganicaRecPanel);
  
        PhRecomendacionPanel phRecomendacionPanel=newJFramePruebaRecomendaciones.otrasRecomendacionesPanel1.PhRecomendacionPanel;
        PhRecomendacionPanelController phRecomendacionPanelController= new PhRecomendacionPanelController(phRecomendacionPanel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public view.OtrasRecomendaciones.OtrasRecomendacionesPanel otrasRecomendacionesPanel1;
    // End of variables declaration//GEN-END:variables
}
