/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.OtrasRecomendaciones;

/**
 *
 * @author Erlinda
 */
public class OtrasRecomendacionesPanel extends javax.swing.JPanel {

    /**
     * Creates new form OtrasRecomendacionesPanel
     */
    public OtrasRecomendacionesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        materiaOrganicaRecPanel1 = new view.OtrasRecomendaciones.MateriaOrganicaRecomendacionPanel();
        PhRecomendacionPanel = new view.OtrasRecomendaciones.PhRecomendacionPanel();

        jTabbedPane1.addTab("tab1", materiaOrganicaRecPanel1);
        jTabbedPane1.addTab("tab2", PhRecomendacionPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public view.OtrasRecomendaciones.PhRecomendacionPanel PhRecomendacionPanel;
    private javax.swing.JTabbedPane jTabbedPane1;
    public view.OtrasRecomendaciones.MateriaOrganicaRecomendacionPanel materiaOrganicaRecPanel1;
    // End of variables declaration//GEN-END:variables
}
